[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
  https://github.com/dkaukov/esp32-afsk.git#e771c98d08fa5e98d5481e5d8e48601631891d57
build_flags =
  -DAUDIO_SAMPLE_RATE=48000
monitor_speed = 115200
